name: CD - Continous Delivery

on:
  push:
    branches: [ main ]

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
  VERCEL_PROJECT_ID_CANVAS: ${{ secrets.VERCEL_PROJECT_ID_CANVAS }}

jobs:
  release_app_web:
    needs:
      - lint_app
      - test_unit_app
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - uses: actions/setup-node@v2
      with:
        node-version: '16'
    - uses: actions/setup-java@v2
      with:
        distribution: 'zulu'
        java-version: '11'
    - uses: subosito/flutter-action@v1
      with:
        flutter-version: '3.0.3'
    - name: "Start: Release Web"
      run: |
        yarn install
        yarn deploy:web:app
        yarn deploy:web:app:canvas
  release_app_android:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: "Start: Release Google Play"
      run: |
        echo "TODO: Deploy Google Play"
  release_app_ios:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: "Start: Release App Store"
      run: |
        echo "TODO: Deploy App Store"
  test_unit_app:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - uses: actions/setup-node@v2
      with:
        node-version: '16'
    - uses: actions/setup-java@v2
      with:
        distribution: 'zulu'
        java-version: '11'
    - uses: subosito/flutter-action@v1
      with:
        flutter-version: '3.0.3'
    - name: "Start: Unit Testing"
      run: |
        yarn install
        yarn test
  lint_app:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - uses: actions/setup-node@v2
      with:
        node-version: '16'
    - uses: actions/setup-java@v2
      with:
        distribution: 'zulu'
        java-version: '11'
    - uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.0.3'
    - name: "Start: Linter"
      run: |
        yarn install
        yarn lint
